version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Clone core library
          command:
            git clone https://github.com/IonLanguage/Ion.git ../Ion
      - run:
          name: Build core library
          command:
            cd ../Ion && dotnet build && cd ../project
      - run:
          name: Restore packages
          command:
            cd IonCLI && dotnet restore && cd ../IonCLI.Tests && dotnet restore && cd ..
      - run:
          name: Build tests
          command:
            cd IonCLI.Tests && dotnet build && cd ..
      - run:
          name: Build project
          command:
            cd IonCLI && dotnet build && cd ..
      - run:
          name: Run tests
          command:
            cd IonCLI.Tests && dotnet test && cd ..
